### ISSUE TITLE
browser name error in 02.14

### ISSUE THREAD

**Issue by schotman** [40fingers/StyleHelper-Sko#2]
at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at FortyFingers.Dnn.SkinObjects.StyleHelper.GetBrowserName()
   at FortyFingers.Dnn.SkinObjects.StyleHelper.GetBrowserClass(Int32 max, String BrowserFilter)
   at FortyFingers.Dnn.SkinObjects.StyleHelper.ProcessTokens(String sOriginal, TextType Type)
   at FortyFingers.Dnn.SkinObjects.StyleHelper.ProcessPageClassTemplate(String Template)
   at FortyFingers.Dnn.SkinObjects.StyleHelper.Page_PreRender(Object sender, EventArgs e)
   at System.Web.UI.Control.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by Timo-Breumelhof** [comment]
I think this is caused by robots that ping the site using an invalid or empty UserAgent string
